= Spring Data Meilisearch

== Client Configuration

This library support using Java based `@Configuration` or XML Namespace for configuring the Meilisearch Client.

The elements in the configuration are:

* `host URL`: The Meilisearch host URL
* `API Key`: The Meilisearch API Key
* `Client Agents`: The `User-Agent` header for the Meilisearch Client

=== Annotation based configuration

[source,java]
----

@Configuration
public class CustomConfiguration extends MeilisearchConfiguration {

    @Override
    public ClientConfiguration clientConfiguration() {
        return ClientConfiguration.builder()
                .connectedToLocalhost()
                .withApiKey("masterKey")
                .build();
    }
}
----

The `host URL` and `API Key` are required configuration.

=== Namespace based configuration

[source,xml]
----
<meilisearch:meilisearch-client id="meilisearchClient" api-key="masterKey"/>
----

The `API Key` is required configuration.
The Host URL is set to `http://localhost:7700` unless otherwise specified.

please refer to the link:src/test/resources/io/vanslog/spring/data/meilisearch/config/namespace.xml[example configuration] in test resources.

== JSON Handler

The `JSON Handler` is used to serialize and deserialize the JSON data.

The following JSON Handlers are supported:

* `com.meilisearch.sdk.json.GsonJsonHandler`
* `com.meilisearch.sdk.json.JacksonJsonHandler`

=== Annotation based configuration

[source,java]
----
public class CustomConfiguration extends MeilisearchConfiguration {

    @Override
    public JsonHandler jsonHandler() {
        return new JacksonJsonHandler();
    }
}
----

The default JSON Handler is `GsonJsonHandler`.
You can use other JSON Handler by overriding the `jsonHandler()` method.

=== Namespace based configuration

[source,xml]
----
<bean id="jsonHandler" class="com.meilisearch.sdk.json.GsonJsonHandler"/>
----

The default JSON Handler is not provided by the XML Namespace.
JSON Handler must be defined as a bean with `id="jsonHandler"`.

== Document Definition

To define the https://www.meilisearch.com/docs/learn/core_concepts/documents[Document], you need to annotate a class with `@Document` annotation.
As an example, the following class defines a `Movie` document with `id`, `title`, `description` and `genres` fields.

[source,java]
----
@Document(indexUid = "movies")
public class Movie {
    @Id private int id;
    private String title;
    private String description;
    private String[] genres;
}
----

=== Index UID

The https://www.meilisearch.com/docs/learn/core_concepts/indexes#index-uid[Index UID] is a unique identifier for an index.
It must be defined for each document with `@Document` annotation.

=== Document id

The https://www.meilisearch.com/docs/learn/core_concepts/primary_key#document-id[Document id] is a unique identifier for a document in an index.
It can be defined with `@Id` annotation or `id` field.
