categories:
  - title: '⭐ New Features'
    label: 'type: enhancement'
  - title: '🐞 Bug Fixes'
    label: 'type: bug'
  - title: '📔 Documentation'
    label: 'type: documentation'
  - title: '🔨 Dependency Upgrades'
    label: 'type: dependency-upgrade'
  - title: '🧰 Maintenance'
    label: 'type: task'

exclude-contributors:
  - 'junghoon-vans'

change-template: '* $TITLE #$NUMBER'
template: |
  ## 📗 Links
  * [Spring Data Meilisearch $RESOLVED_VERSION Reference documentation](https://junghoon-vans.github.io/spring-data-meilisearch/$RESOLVED_VERSION/)
  * [Spring Data Meilisearch $RESOLVED_VERSION Javadoc](https://junghoon-vans.github.io/spring-data-meilisearch/$RESOLVED_VERSION/api/java/index.html)

  $CHANGES
  
  ## ❤️ Contributors
  We'd like to thank all the contributors who worked on this release!
  
  $CONTRIBUTORS
