= Testing

== Run the tests

[source,bash]
----
./mvnw test
----

== Create integration test

To create an integration test, you need to add the following annotation to your test class:

[source,java]
----
@MeilisearchTest
@ContextConfiguration(classes = {MeilisearchTestConfiguration.class})
class MeilisearchTest {

    @Autowired
    Client client;

    @Test
    void test() {
        // ...
    }
}
----

The `MeilisearchTest` annotation means that the test is run in integration with Meilisearch.
This code makes it easy to run the container.
`MeilisearchTestConfiguration` is a configuration class for providing a `Client` associated with a container run by MeilisearchTest.

The default container image is pinned to the latest stable Meilisearch release, `v1.54.0`.
The minimum supported Meilisearch release is `v1.27.0`, exercised by
`SortableMeilisearchRepositoryIntegrationTests` using an explicit image tag.
Give tests for different server versions distinct `@ContextConfiguration` configuration types
so Spring does not reuse a context bound to another container.
