[[meilisearch.operations]]
= Meilisearch Operations

Spring Data Meilisearch uses several interfaces to define the operations that can be called against a Meilisearch index.

* `DocumentOperations` defines actions to store, update and retrieve entities based on their id.
* `SearchOperations` define the actions to search for multiple entities using queries
* `MeilisearchOperations` combines the `DocumentOperations` and `SearchOperations` interfaces.

These interfaces correspond to the structuring of the https://www.meilisearch.com/docs/reference/api/overview[Meilisearch API].

The default implementations of the interfaces offer:

* Read/Write mapping support for domain types
* A rich query API
* Resource management and Exception translation

[[meilisearch.operations.usage]]
== Usage examples

The example shows how to use an injected `MeilisearchOperations` instance in a Spring REST controller.
The example assumes that `Movie` is a class that is annotated with `@Document`, `@Id` etc.

.MeilisearchOperations usage
====
[source,java]
----
@RestController
@RequestMapping("/")
public class MovieController {

  private MeilisearchOperations meilisearchOperations;

  public MovieController(MeilisearchOperations meilisearchOperations) { <.>
    this.meilisearchOperations = meilisearchOperations;
  }

  @PostMapping("/movie")
  public String save(@RequestBody Movie movie) {                        <.>
    Movie savedEntity = meilisearchOperations.save(movie);
    return savedEntity.getId();
  }

  @GetMapping("/movie/{id}")
  public Movie findById(@PathVariable("id") String id) {               <.>
    return meilisearchOperations.get(id, Movie.class);
  }
}
----

<.> Let Spring inject the provided `MeilisearchOperations` bean in the constructor
<.> Store a movie in the Meilisearch instance
<.> Retrieve the movie with a get by id
====

[[meilisearch.operations.searchresulttypes]]
== Search Result Types

When searching with the methods of the `SearchOperations` interface, additional information is available for each entity.

The following classes and interfaces are available:

.SearchHit<T>
Contains the following information:

* The retrieved entity of type <T>

.SearchHits<T>
Contains the following information:

* A list of `SearchHit<T>` objects
* Processing time
* Query information

[[meilisearch.operations.queries]]
== Queries

The `SearchOperations` interface methods take different `Query` parameters that define the query to execute.
Spring Data Meilisearch provides several implementations: `BasicQuery`, `IndexQuery`, and `FacetQuery`.

[[meilisearch.operations.basicquery]]
=== BasicQuery

`BasicQuery` is the standard implementation for simple search queries:

.Search for movies with a given title
====
[source,java]
----
Query query = BasicQuery.builder()
    .withQ("Wonder Woman")
    .build();
----
====

[[meilisearch.operations.indexquery]]
=== IndexQuery

`IndexQuery` is used for multi-search operations:

====
[source,java]
----
List<IndexQuery> queries = List.of(
    new IndexQuery("Wonder Woman"),
    new IndexQuery("Batman")
);
----
====

[[meilisearch.operations.facetquery]]
=== FacetQuery

`FacetQuery` is used for faceted search operations:

====
[source,java]
----
FacetQuery query = FacetQuery.builder()
    .withFacetName("genres")
    .withFacetQuery("act")
    .build();
----
====
