[[meilisearch.settings]]
= Meilisearch Settings

This chapter covers how to modify search https://www.meilisearch.com/docs/reference/api/settings[settings] in Meilisearch.

[[meilisearch.settings.overview]]
== Overview

Meilisearch settings are used to define the behavior of the search engine.
Using `@Setting` annotation, you can define the basic settings for the index, while complex settings are defined using separate annotations like `@TypoTolerance`, `@Faceting`, and `@Pagination`.

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  searchableAttributes = { "description", "brand", "color" },
  displayedAttributes = { "description", "brand", "color", "productId" },
  sortableAttributes = { "productId" },
  rankingRules = { "typo", "words", "proximity", "attribute", "sort", "exactness" },
  distinctAttribute = "productId",
  filterableAttributes = { "brand", "color", "price" },
  synonyms = {
        @Synonym(word = "phone", synonyms = { "mobile", "cellphone" }),
        @Synonym(word = "laptop", synonyms = { "notebook" })
  },
  dictionary = { "netflix", "spotify" },
  stopWords = { "a", "an", "the" },
  separatorTokens = { "-", "_", "@" },
  nonSeparatorTokens = { ".", "#" },
  proximityPrecision = "byWord",
  searchCutoffMs = 50
)
@TypoTolerance(
  enabled = true,
  minWordSizeForTypos = @MinWordSizeForTypos(oneTypo = 5, twoTypos = 9),
  disableOnWords = {"skype", "zoom"},
  disableOnAttributes = {"serial_number"}
)
@Faceting(maxValuesPerFacet = 100)
@Pagination(maxTotalHits = 2000)
class Product {
    @Id private String id;
    private String description;
    private String brand;
    private String color;
    private String productId;
    private double price;
}
----
====

[[meilisearch.settings.search]]
== Search Settings

These settings control how documents are searched and ranked in Meilisearch.

[[meilisearch.settings.search.attributes]]
=== Searchable and Displayed Attributes

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  searchableAttributes = { "description", "brand", "color" },        <.>
  displayedAttributes = { "description", "brand", "color", "productId" } <.>
)
class Product {
    @Id private String id;
    private String description;
    private String brand;
    private String color;
    private String productId;
}
----

<.> The `searchableAttributes` attribute is used to define the fields that must be used for searching the results.
<.> The `displayedAttributes` attribute is used to define the fields that must be displayed in the results.
====

[[meilisearch.settings.search.ranking]]
=== Ranking and Sorting

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  sortableAttributes = { "productId" },                                              <.>
  rankingRules = { "typo", "words", "proximity", "attribute", "sort", "exactness" }, <.>
  distinctAttribute = "productId"                                                    <.>
)
class Product {
    @Id private String id;
    private String productId;
    // other fields...
}
----

<.> The `sortableAttributes` attribute is used to define the fields that can be used for sorting the results.
<.> The `rankingRules` attribute is used to define the ranking rules that must be used for sorting the results.
<.> The `distinctAttribute` attribute is used to define the field that must be used to remove duplicates from the results.
====

[[meilisearch.settings.search.filtering]]
=== Filtering and Faceting

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  filterableAttributes = { "brand", "color", "price" }                               <.>
)
@Faceting(maxValuesPerFacet = 100)                                                   <.>
class Product {
    @Id private String id;
    private String brand;
    private String color;
    private double price;
    // other fields...
}
----

<.> The `filterableAttributes` attribute defines which fields can be used for filtering and faceted search.
<.> The `@Faceting` annotation configures faceted search behavior.
====

[[meilisearch.settings.search.text]]
== Text Processing Settings

These settings control how Meilisearch processes text during indexing and searching.

[[meilisearch.settings.search.text.synonyms]]
=== Synonyms and Dictionary

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  synonyms = {                                                                       <.>
        @Synonym(
            word = "phone",
            synonyms = { "mobile", "cellphone" }
        ),
        @Synonym(
            word = "laptop",
            synonyms = { "notebook" }
        )
  },
  dictionary = { "netflix", "spotify" },                                             <.>
  stopWords = { "a", "an", "the" }                                                   <.>
)
class Product {
    @Id private String id;
    // fields...
}
----

<.> The `synonyms` attribute defines groups of words that should be considered equivalent in search.
<.> The `dictionary` attribute adds custom words to the internal dictionary.
<.> The `stopWords` attribute is used to define the stop words that must be used for searching the results.
====

[[meilisearch.settings.search.text.typo]]
=== Typo Tolerance

====
[source,java]
----
@Document(indexUid = "products")
@TypoTolerance(                                                                      <.>
  enabled = true,
  minWordSizeForTypos = @MinWordSizeForTypos(
    oneTypo = 5,
    twoTypos = 9
  ),
  disableOnWords = {"skype", "zoom"},
  disableOnAttributes = {"serial_number"}
)
class Product {
    @Id private String id;
    // fields...
}
----

<.> The `@TypoTolerance` annotation configures the typo tolerance behavior of the search engine.
====

[[meilisearch.settings.search.text.tokenization]]
=== Tokenization

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  separatorTokens = { "-", "_", "@" },                                               <.>
  nonSeparatorTokens = { ".", "#" }                                                  <.>
)
class Product {
    @Id private String id;
    // fields...
}
----

<.> The `separatorTokens` attribute defines which characters should be considered as word separators.
<.> The `nonSeparatorTokens` attribute defines which characters should not be considered as word separators.
====

[[meilisearch.settings.search.text.localization]]
=== Localization

By default, Meilisearch automatically detects the languages used in your documents.
However, you can explicitly define which languages are present in your dataset and in which fields using localized attributes configuration.
You can configure localized attributes using the `@LocalizedAttribute` annotation within the `@Setting` annotation.
Note that configuring multiple languages for a single index may impact search performance.

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  localizedAttributes = {
    @LocalizedAttribute(
      attributePatterns = { "*En" },                                                <.>
      locales = { "eng" }                                                           <.>
    )
  }
)
class Product {
    @Id private String id;
    private String nameEn;
    // fields...
}
----

<.> The `attributePatterns` specify which fields contain content in the specified languages using patterns.
These patterns support wildcards (*) to match multiple fields with similar naming conventions:
* `*En` matches fields ending with "En" (e.g., "nameEn", "titleEn") These fields will be processed according to the language rules of the specified locales.
The patterns affect `searchableAttributes`, `filterableAttributes`, and `sortableAttributes`.
<.> The `locales` attribute defines the list of supported languages for the specified attributes.
Each locale follows the ISO-639-3 three-letter, or alternatively use ISO-639-1 two-letter equivalents.
For a complete list of supported languages, refer to the https://www.meilisearch.com/docs/reference/api/settings#locales[Meilisearch documentation].
====

==== Language Detection Control

Meilisearch provides two mechanisms for controlling language detection:

* *Query-level Language Control*: If Meilisearch is detecting incorrect languages because of the query text, you can explicitly set the search language using the `locales` parameter in your search request.
* *Document-level Language Control*: If Meilisearch is detecting incorrect languages in your documents, use `localizedAttributes` to explicitly set the document languages at the index level.

For complete control over language detection during both indexing and search time, you can use both `locales` and `localizedAttributes` together.

[[meilisearch.settings.performance]]
== Performance Settings

These settings control the performance aspects of Meilisearch.

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  proximityPrecision = "byWord",                                                     <.>
  searchCutoffMs = 50                                                                <.>
)
class Product {
    @Id private String id;
    // fields...
}
----

<.> The `proximityPrecision` attribute defines how word proximity is calculated ("byWord", "byAttribute")
<.> The `searchCutoffMs` attribute sets the maximum processing time for a search query in milliseconds.
====

[[meilisearch.settings.pagination]]
== Pagination

Meilisearch's search function is limited to return a maximum of 1,000 results.
Therefore, `search(SearchRequest searchRequest, Class<?> clazz)` in MeilisearchOperation can't return more than 1,000 results.

If you have more than 1,000 results, you must use `@Pagination` annotation to extract the remaining results.

====
[source,java]
----
@Document(indexUid = "products")
@Pagination(maxTotalHits = 2000)                                                     <.>
class Product {
    @Id private String id;
    // fields...
}
----

<.> The `maxTotalHits` is used to define the maximum number of results that can be returned by the search engine.
====
