[[meilisearch.settings]]
= Meilisearch Settings

This chapter covers how to modify search https://www.meilisearch.com/docs/reference/api/settings[settings] in Meilisearch.

[[meilisearch.settings.overview]]
== Overview

Meilisearch settings are used to define the behavior of the search engine.
Using `@Setting` annotation, you can define the settings for the index.

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  sortableAttributes = { "productId" },                                              <.>
  distinctAttribute = "productId",                                                   <.>
  searchableAttributes = { "description", "brand", "color" },                        <.>
  displayedAttributes = { "description", "brand", "color", "productId" },            <.>
  rankingRules = { "typo", "words", "proximity", "attribute", "sort", "exactness" }, <.>
  stopWords = { "a", "an", "the" },                                                  <.>
  filterableAttributes = { "brand", "color", "price" },                              <.>
  synonyms = {                                                                       <.>
        @Synonym(
            word = "phone",
            synonyms = { "mobile", "cellphone" }
        ),
        @Synonym(
            word = "laptop",
            synonyms = { "notebook" }
        )
  },
  typoTolerance = @TypoTolerance(                                                    <.>
    enabled = true,
    minWordSizeForTypos = @MinWordSizeForTypos(
      oneTypo = 5,
      twoTypos = 9
    ),
    disableOnWords = {"skype", "zoom"},
    disableOnAttributes = {"serial_number"}
  ),
  faceting = @Faceting(                                                              <.>
    maxValuesPerFacet = 100
  ),
  dictionary = { "netflix", "spotify" },                                             <.>
  proximityPrecision = "byWord",                                                     <.>
  searchCutoffMs = 50,                                                               <.>
  separatorTokens = { "-", "_", "@" },                                               <.>
  nonSeparatorTokens = { ".", "#" }                                                  <.>
)
class Product {
    @Id private String id;
    private String description;
    private String brand;
    private String color;
    private String productId;
    private double price;
}
----

<.> The `sortableAttributes` attribute is used to define the fields that can be used for sorting the results.
<.> The `distinctAttribute` attribute is used to define the field that must be used to remove duplicates from the results.
<.> The `searchableAttributes` attribute is used to define the fields that must be used for searching the results.
<.> The `displayedAttributes` attribute is used to define the fields that must be displayed in the results.
<.> The `rankingRules` attribute is used to define the ranking rules that must be used for sorting the results.
<.> The `stopWords` attribute is used to define the stop words that must be used for searching the results.
<.> The `filterableAttributes` attribute defines which fields can be used for filtering and faceted search.
<.> The `synonyms` attribute defines groups of words that should be considered equivalent in search.
<.> The `typoTolerance` attribute configures the typo tolerance behavior of the search engine.
<.> The `faceting` attribute configures faceted search behavior.
<.> The `dictionary` attribute adds custom words to the internal dictionary.
<.> The `proximityPrecision` attribute defines how word proximity is calculated ("byWord", "byAttribute")
<.> The `searchCutoffMs` attribute sets the maximum processing time for a search query in milliseconds.
<.> The `separatorTokens` attribute defines which characters should be considered as word separators.
<.> The `nonSeparatorTokens` attribute defines which characters should not be considered as word separators.
====

[[meilisearch.settings.pagination]]
== Pagination

Meilisearch's search function is limited to return a maximum of 1,000 results.
Therefore, `search(SearchRequest searchRequest, Class<?> clazz)` in MeilisearchOperation can't return more than 1,000 results.

If you have more than 1,000 results, you must use `@Pagination` annotation to extract the remaining results.

====
[source,java]
----
@Document(indexUid = "products")
@Setting(
  pagination = @Pagination(maxTotalHits = 2000)                                       <.>
)
class Product {
    @Id private String id;
    private String description;
    private String brand;
    private String color;
    private String productId;
    private double price;
}
----

<.> The `maxTotalHits` is used to define the maximum number of results that can be returned by the search engine.
====
