[[meilisearch.client]]
= Meilisearch Client

This library support using Java based `@Configuration` or XML Namespace for configuring the Meilisearch Client.

The elements in the configuration are:

* `host URL`: The Meilisearch host URL
* `API Key`: The Meilisearch API Key
* `Client Agents`: The `User-Agent` header for the Meilisearch Client

[[meilisearch.client.configuration]]
== Client Configuration

[[meilisearch.client.configuration.annotation]]
=== Annotation based configuration

[source,java]
----

@Configuration
public class CustomConfiguration extends MeilisearchConfiguration {

    @Override
    public ClientConfiguration clientConfiguration() {
        return ClientConfiguration.builder()
                .connectedToLocalhost()
                .withApiKey("masterKey")
                .build();
    }
}
----

The `host URL` and `API Key` are required configuration.

[[meilisearch.client.configuration.namespace]]
=== Namespace based configuration

[source,xml]
----
<meilisearch:meilisearch-client id="meilisearchClient" api-key="masterKey"/>
----

The `API Key` is required configuration.
The Host URL is set to `http://localhost:7700` unless otherwise specified.

please refer to the link:../../../../src/test/resources/io/vanslog/spring/data/meilisearch/config/namespace.xml[example configuration] in test resources.

[[meilisearch.json-handler]]
== JSON Handler

The `JSON Handler` is used to serialize and deserialize the JSON data.

The following JSON Handlers are supported:

* `com.meilisearch.sdk.json.GsonJsonHandler`
* `com.meilisearch.sdk.json.JacksonJsonHandler`

[[meilisearch.json-handler.configuration.annotation]]
=== Annotation based configuration

[source,java]
----
public class CustomConfiguration extends MeilisearchConfiguration {

    @Override
    public JsonHandler jsonHandler() {
        return new JacksonJsonHandler();
    }
}
----

The default JSON Handler is `GsonJsonHandler`.
You can use other JSON Handler by overriding the `jsonHandler()` method.

[[meilisearch.json-handler.configuration.namespace]]
=== Namespace based configuration

[source,xml]
----
<bean id="jsonHandler" class="com.meilisearch.sdk.json.GsonJsonHandler"/>
----

The default JSON Handler is not provided by the XML Namespace.
JSON Handler must be defined as a bean with `id="jsonHandler"`.

