[[meilisearch.document]]
= Meilisearch Document

Spring Data Meilisearch provides a simple way to define a https://www.meilisearch.com/docs/learn/core_concepts/documents[Document].

[[meilisearch.document.definition]]
== Document definition

To define the https://www.meilisearch.com/docs/learn/core_concepts/documents[Document], you need to annotate a class with `@Document` annotation.
As an example, the following class defines a `Movie` document with `id`, `title`, `description` and `genres` fields.

.The sample document
====
[source,java]
----
import io.vanslog.spring.data.meilisearch.annotations.Document;

import org.springframework.data.annotation.Id;

@Document(indexUid = "movies")
public class Movie {
    @Id private int id;
    private String title;
    private String description;
    private String[] genres;
}
----
====

[[meilisearch.document.index-uid]]
== Index UID

The https://www.meilisearch.com/docs/learn/core_concepts/indexes#index-uid[Index UID] is a unique identifier for an index.
It can be defined explicitly with the `indexUid` attribute in the `@Document` annotation.

.Explicit Index UID
====
[source,java]
----
@Document(indexUid = "movies")
public class Movie {
    // fields
}
----
====

If the `indexUid` is not specified or the class is not annotated with `@Document`, the class name will be used as the index UID by default.

.Default Index UID (using class name)
====
[source,java]
----
// No @Document annotation or no indexUid specified
public class Movie {
    // fields
}
----
====

In this case, "Movie" will be used as the index UID

[[meilisearch.document.id]]
== Document id

The https://www.meilisearch.com/docs/learn/core_concepts/primary_key#document-id[Document id] is a unique identifier for a document in an index.
It can be defined with `@Id` annotation or `id` field.
