[[meilisearch.client]]
= Meilisearch Client
:page-section-summary-toc: 1

This chapter describes configuration and usage of the Meilisearch client.

Spring Data Meilisearch operates upon a `Meilisearch Client` (provided by https://github.com/meilisearch/meilisearch-java[Meilisearch Java]) that is connected to a single Meilisearch instance.

[[meilisearch.client.annotation]]
== Annotation based configuration

The Spring Data Meilisearch client can be configured using the `@Configuration` annotation.

.Spring Data Meilisearch client using JavaConfig
====
[source,java]
----
import io.vanslog.spring.data.meilisearch.client.ClientConfiguration;
import io.vanslog.spring.data.meilisearch.config.MeilisearchConfiguration;

import org.springframework.context.annotation.Configuration;

@Configuration
public class MyClientConfig extends MeilisearchConfiguration {

    @Override
    public ClientConfiguration clientConfiguration() {
        return ClientConfiguration.builder()           <.>
                .connectedToLocalhost()
                .withApiKey("masterKey")
                .build();
    }
}
----

<.> For a detailed description of the builder methods see xref:#meilisearch.client.configuration[Client Configuration].
====

[[meilisearch.client.namespace]]
== Spring Namespace

The Spring Data Meilisearch client can be configured using the Spring XML namespace.

.Spring Data Meilisearch client using XML Namespace
====
[source,xml]
----
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:meilisearch="http://www.vanslog.io/spring/data/meilisearch"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.vanslog.io/spring/data/meilisearch
       http://www.vanslog.io/spring/data/meilisearch/spring-meilisearch-1.0.xsd">

    <meilisearch:meilisearch-client id="meilisearchClient" api-key="masterKey"/>

</beans>
----
====

IMPORTANT: When setting up a client using the Spring namespace, a JSON handler must be set up.
Use the xref:#meilisearch.json-handler.namespace[JSON handler namespace configuration].

[[meilisearch.client.configuration]]
== Client Configuration

Configuration options are provided by the `ClientConfiguration` builder.

.Client Configuration
====
[source,java]
----
String[] agents = {"Spring Data Meilisearch"};                          <.>

ClientConfiguration clientConfiguration = ClientConfiguration.builder()
    .connectedTo("http://localhost:7700")                               <.>
    .withApiKey("masterKey")                                            <.>
    .withClientAgents(agents)                                           <.>
    .withRequestTimeout(2000)                                           <.>
    .withRequestInterval(20)                                            <.>
    .build();
----

<.> Define the client agents that will be sent as a `User-Agent` header to Meilisearch.
<.> Use the builder to provide the Meilisearch host URL.
<.> Set the Meilisearch API Key to use for authentication.
<.> Set the client agents.
<.> Set the request timeout to 2000 milliseconds.
<.> Set the request interval to 20 milliseconds.
====

[[meilisearch.json-handler]]
== JSON handler

The `JSON handler` configures the underlying Meilisearch Java SDK transport.
Entity document mapping and document JSON payloads are handled by Spring Data Meilisearch through
`MeilisearchConverter` and the `meilisearchObjectMapper` bean.

[[meilisearch.json-handler.supported]]
=== Supported JSON handlers

The following JSON handlers are supported:

* `com.meilisearch.sdk.json.GsonJsonHandler`
* `com.meilisearch.sdk.json.JacksonJsonHandler`
* Custom JSON handler that implements `com.meilisearch.sdk.json.JsonHandler`

[[meilisearch.json-handler.annotation]]
=== Annotation based configuration

You don't need to provide a JSON handler if you are using the default JSON handler, `GsonJsonHandler`.
But you can override the `jsonHandler()` method to provide a custom JSON handler.

.Setting JSON handler using JavaConfig
====
[source,java]
----
import io.vanslog.spring.data.meilisearch.config.MeilisearchConfiguration;

import com.meilisearch.sdk.json.JacksonJsonHandler;
import com.meilisearch.sdk.json.JsonHandler;

import org.springframework.context.annotation.Configuration;

@Configuration
public class JsonHandlerConfig extends MeilisearchConfiguration {

    @Override
    public JsonHandler jsonHandler() {
        return new JacksonJsonHandler();    <.>
    }
}
----

<.> Use Jackson JSON handler instead of the default JSON handler.
====

[[meilisearch.json-handler.namespace]]
=== Spring Namespace

Register a JSON handler bean and reference it from `<meilisearch:meilisearch-client>` using `json-handler-ref`.
If `json-handler-ref` is omitted, the default bean name is `jsonHandler`.

.Setting JSON handler using XML Namespace
====
[source,xml]
----
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:meilisearch="http://www.vanslog.io/spring/data/meilisearch"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.vanslog.io/spring/data/meilisearch
       http://www.vanslog.io/spring/data/meilisearch/spring-meilisearch-1.0.xsd">

    <bean id="jsonHandler" class="com.meilisearch.sdk.json.GsonJsonHandler"/>

    <meilisearch:meilisearch-client
        id="meilisearchClient"
        api-key="masterKey"
        json-handler-ref="jsonHandler"/>

</beans>
----
====
