# PACKAGES antora@3.2.0-alpha.6 @antora/atlas-extension@1.0.0-alpha.2 @antora/collector-extension@1.0.0-alpha.7 @springio/antora-extensions@1.13.0 @asciidoctor/tabs@1.0.0-beta.6 @springio/asciidoctor-extensions@1.0.0-alpha.11
#
# Authoring/PR preview playbook: keep this HEAD-only for local changes and pull request previews.
antora:
  extensions:
    - require: '@springio/antora-extensions'
      root_component_name: 'data-meilisearch'
site:
  title: Spring Data Meilisearch
  url: https://junghoon-vans.github.io/spring-data-meilisearch/
content:
  sources:
    - url: ./../../..
      branches: HEAD
      start_path: src/main/antora
      worktrees: true
    - url: https://github.com/spring-projects/spring-data-commons
      # Refname matching:
      # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches: [ main ]
      start_path: src/main/antora
asciidoc:
  attributes:
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/javadoc-extension'
  sourcemap: true
urls:
  latest_version_segment: ''
runtime:
  fetch: true
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.16/ui-bundle.zip
    snapshot: true
